name: Crawl Naver Economy News

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC = 한국 시간 오전 9시쯤
  workflow_dispatch:      # 수동 실행도 가능

permissions:
  contents: write         # GitHub Actions가 repo에 push할 수 있게 허용

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      run: |
        pip install uv

    - name: Install dependencies with uv
      run: |
        uv pip install -r requirements.txt --system

    - name: Run crawling script
      run: |
        python -m learning_crawling.crawling_economy_news

    - name: Commit and push if changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add news_titles.csv
        DATE=$(date +"%Y-%m-%d")
        git commit -m "Update news_titles.csv - $DATE" || echo "No changes to commit"
        git push
